plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\xampp\\htdocs\\Pengembangan-Aplikasi-Point-Of-Sale-untuk-Event"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]